### ISSUE TITLE
Set up JupyterHub

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/python-camp#29]
Test with JupyterLab and MyST rendering for JL.

**Comment by dolsysmith** [comment]
## Testing setup

### Docker Compose file

```
version: "3.8"
services:

  jupyterhub:
    image: jupyterhub/jupyterhub
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - /opt/jupyterhub/jupyterhub:/srv/jupyterhub
    command: jupyterhub
    environment:
      - VIRTUAL_HOST=[your-hostname.com]
      - VIRTUAL_PORT=8000

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```
### Additional setup

- Create an `opt/jupyterhub/jupyterhub` directory to store the config file
- Shell into the jupyterhub container: `docker exec -it jupyterhub-jupyterhub-1 bash`
- Install jupyterlab & notebook: `pip3 install jupyterlab notebook`
- Create a config file: `jupyterhub --generate-config` (Config file will be stored in the linked volume from the docker-compose file)
- Create a test user: `useradd -m -d /home/jupytertest -p password jupytertest`
- Exit the container
- Uncomment the following line in `/opt/jupyterhub/jupyterhub/jupyterhub_config.py`:
   ```
      c.JupyterHub.base_url = '/jupyter/'
   ```
- Restart the container

### Use
 
Browse to `[your-hostname.com]/jupyter` and log in as the test user you created above.
